server:
  host: 0.0.0.0
  port: 18000
  context: /toolbox
  data: ./data

#日志配置
logging:
  level:
    root: ERROR
    com.teamide: INFO
  file:
    name: ./logs/toolbox.log
  pattern:
    file: '[:%d:] [:%-5level:] [:%thread:] [:%c:%M:] [:%m:]%n'