#server
server:
  host: ${server.host:0.0.0.0}
  port: ${server.port:18000}
  servlet:
    context-path: ${server.context:/toolbox}
    session:
      timeout: ${server.timeout:7200}

#spring配置
spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

#数据目录
data:
  dir: ${teamide-toolbox-data:./data}
