/* Model Coder File Mark */
/** The current file is generated by Model Coder, please do not modify and move! **/
package com.teamide.toolbox.bean;

import java.io.Serializable;

/**
 * 请求对象
 * 
 * 包含请求参数、请求body、请求header、session数据等
 * 
 * @author Model Coder
 */
public class RequestBean implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

}
