/* Model Coder File Mark */
/** The current file is generated by Model Coder, please do not modify and move! **/
package com.teamide.toolbox.bean;


/**
 * Java Code
 * 
 * @author Model Coder
 **/
public class WebSessionBean {
	

}
