# 服务配置，配置IP、端口等
[server]
host = '0.0.0.0'
port = 18000
context = '/toolbox'
data = './data'

# 用户配置，配置用户名密码进行登录，角色：1：管理员（所有功能）、2：观察员（只读功能）
[[user]]
name = 'admin'
auth = '123456'
role = 1
[[user]]
name = 'user1'
auth = '123456'
role = 2

# Redis配置，默认填充该配置在页面，可以配置多个
[[redis]]
address = '127.0.0.1:6379'
auth = ''
[[redis]]
address = '127.0.0.2:6379'
auth = ''

# Zookeeper配置，默认填充该配置在页面，可以配置多个
[[zookeeper]]
address = '127.0.0.1:2181'
[[zookeeper]]
address = '127.0.0.2:2181'

# Kafka配置，默认填充该配置在页面，可以配置多个
[[kafka]]
address = '127.0.0.1:9092'
[[kafka]]
address = '127.0.0.2:9092'

# Database配置，默认填充该配置在页面，可以配置多个
[[database]]
type = 'mysql'
host = '127.0.0.1'
port = 3306
username = 'root'
password = '123456'
[[database]]
type = 'mysql'
host = '127.0.0.2'
port = 3306
username = 'root'
password = '123456'