/* Model Coder File Mark */
/** The current file is generated by Model Coder, please do not modify and move! **/
package com.teamide.toolbox.util;

import java.io.Serializable;

/**
 * 数据字典配置项
 * 
 * 配置值、文案、配色等
 * 
 * @author Model Coder
 */
public class OptionBean implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	// 字典值
	private String value;

	// 值说明
	private String text;

	// 配色，可用于前端分色展示
	private String color;

	public OptionBean() {
	}

	public OptionBean(String value, String text) {
		this.value = value;
		this.text = text;
	}

	public OptionBean(String value, String text, String color) {
		this(value, text);
		this.color = color;
	}

	public String getColor() {
		return color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	public String getValue() {
		return value;
	}

	public String getText() {
		return text;
	}

}
