/* Model Coder File Mark */
/** The current file is generated by Model Coder, please do not modify and move! **/
package com.teamide.toolbox.component;

/**
 * AppConstant
 * 
 * 应用常量
 * 
 * @author Model Coder
 */
public class Constant {

	/**
	 * request session key
	 **/
	public static final String SESSION_KEY = "server_session_key";

}
