/* Model Coder File Mark */
/** The current file is generated by Model Coder, please do not modify and move! **/
package com.teamide.toolbox.component;

/**
 * Errcode
 * 
 * 应用错误码
 * 
 * @author Model Coder
 */
public class Errcode {

    /**
	 * 成功
	 **/
    public static final Errcode SUCCESS = new Errcode("0", "成功");

    /**
	 * 失败
	 **/
    public static final Errcode FAIL = new Errcode("-1", "失败");

    /**
	 * 参数不存在
	 **/
    public static final Errcode PARAM_IS_NULL = new Errcode("10101", "参数不存在！");

    /**
	 * 参数已存存在
	 **/
    public static final Errcode PARAM_IS_NOT_NULL = new Errcode("10101", "参数已存存在！");

    /**
	 * 参数不存在或为空
	 **/
    public static final Errcode PARAM_IS_EMPTY = new Errcode("10102", "参数不存在或为空！");

    /**
	 * 参数不为空
	 **/
    public static final Errcode PARAM_IS_NOT_EMPTY = new Errcode("10102", "参数存在且不为空！");

    /**
	 * 参数验证失败
	 **/
    public static final Errcode PARAM_VALIDATE_FAIL = new Errcode("10103", "参数验证失败！");
	
    private final String code;

    private final String msg;

    public Errcode(String code, String msg) {
        this.code = code;
        this.msg = msg;
    }

    public String getCode() {
        return code;
    }

    public String getMsg() {
        return msg;
    }
}
